### ISSUE TITLE
Node v.7.0.0 (node:2368) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

### ISSUE THREAD

**Issue by unlight** [fuse-box/angular2-example#1]
Node v.7.0.0, Win 8.1
3 times warning message appearing:
`(node:2368) DeprecationWarning: Calling an asynchronous function without callback is deprecated.`

Do not know where it's come from.

**Comment by nchanged** [comment]
Thanks, i will take a look.

**Comment by nchanged** [comment]
Thank you very much for submitting the issue. It has been fixed in `1.2.100`
Next time please use [fuse-box](https://github.com/fuse-box/fuse-box) repository. It's easier to track.

Cheers
