### ISSUE TITLE
Demo doesn't work in IE 11

### ISSUE THREAD

**Issue by tsawan** [fuse-box/angular2-example#26]
I am on a Windows 7 machine with IE 11.
The demo at https://fuse-box.github.io/angular2-example/ just hangs on "Loading app..." message and there's a syntax error in IE console.

It works fine in Edge browser.

**Comment by devmondo** [comment]
maybe some js code not supported by IE 11 ?
what is the error exactly ?

**Comment by tsawan** [comment]
Just a "Syntax Error" in the app.js bundle on "let" keyword. 
I also tried to target es5 in tsconfig.json but that resulted in some other errors.

**Comment by tsawan** [comment]
please any update? or IE 11 is not supported?

**Comment by nchanged** [comment]
Sorry i missed that one.
@tsawan could you try removing `.fusebox` folder please and try again?
And there might be an issue with HMR (code might be not transpiled)

**Comment by devmondo** [comment]
@tsawan 

if you could dig more what errors it would be helpful, but most probably it is angular that needs polyfills, because they use es6 features not supported in IE, check this page it might help
https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by tsawan** [comment]
thanks @devmondo.
After importing core-js/es6 and changing target to es5 in tsconfig.json, it now works in IE 11.

**Comment by devmondo** [comment]
perfect :)
