### ISSUE TITLE
Example throws TypeError in browser

### ISSUE THREAD

**Issue by ghost** [fuse-box/angular2-example#9]
Was trying it out but encountered the following error.

![image](https://cloud.githubusercontent.com/assets/8189808/22826163/4a4885ce-ef91-11e6-8017-e3cd8bd3b89e.png)

**Comment by nchanged** [comment]
Which project? What's your setup? Can share the config please.

**Comment by nchanged** [comment]
Oh i am sorry, lemme check

**Comment by ghost** [comment]
Well this angular2-example on Windows 10 64bit node 7.x

**Comment by nchanged** [comment]
Ok, I bumped the version, but I fear you got something else there. 
```
node fuse.js
```
And then visit `localhost:4445`

That's how you do it right? 
Can you try upgrading FuseBox?
```
npm update fuse-box --save-dev
```

**Comment by ghost** [comment]
Same result.

**Comment by nchanged** [comment]
Ok, so it's just hot-reload that is bugging up right? Do you see the project itself?

**Comment by ghost** [comment]
no, i don't see anything but Loading...

**Comment by nchanged** [comment]
Concluded - again caching issue.
